server:
  port: 9004

spring:
  application:
    name: PAYMENTS-SERVICE
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
